services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    expose:
      - "8000" 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"  # For HTTPS later
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
volumes:
  downloads: